# Generated by Django 4.2.6 on 2023-10-21 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='file',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='content',
            field=models.TextField(),
        ),
    ]
